[features]
seeds = false
[programs.devnet]
solstay_key_program = "8PCTb312rhuBU7pM1btq6Dy9XPjrEnqEPQySxxADRjGA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/baileyspraggins/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
